title: Computational Chemistry
description: Guides and resources for HPC-based computational chemistry
url: https://zliasi.github.io
baseurl: /compchem

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation
nav_enabled: true
nav_sort: order

# Footer content
footer_content: "Copyright &copy; 2025 Zacharias Liasi. Distributed under the MIT License."

# Code highlighting
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Plugins
plugins:
  - jekyll-seo-tag

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Aux links (top right corner)
aux_links:
  "View on GitHub":
    - "https://github.com/zliasi/compchem"

aux_links_new_tab: true
